services:
  app:
    image: ghcr.io/nerdgeschoss/nerdgeschoss/development-environment:3.3-22
    user: root
    volumes:
      - ../..:/workspaces:cached
      - ~/.netrc:/root/.netrc
      - ~/.ssh:/root/.ssh
      - ~/.config/gh:/root/.config/gh
      - ~/.cache/devcontainer/playwright:/root/.cache/devcontainer/playwright
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    environment:
      TZ: Europe/Berlin
      EDITOR: code --wait

    working_dir: /workspace
