source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read("../../.ruby-version").strip

gem "shimmer", path: "../.."

gem "rails", "~> 7.0.4"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "jsbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "cssbundling-rails"
gem "jbuilder"
gem "redis", "~> 4.0"
gem "bootsnap", require: false
gem "sassc-rails"
gem "dotenv"
gem "slim-rails"
gem "awesome_print"
gem "dotenv-rails"

group :development, :test do
  gem "rspec-rails"
  gem "rspec-retry"
  gem "pry"
  gem "pry-rails"
  gem "pry-byebug"
  gem "pry-doc"
  gem "guard"
  gem "guard-rspec"
  gem "capybara"
  gem "rack_session_access"
  gem "cuprite"
  gem "rubocop"
  gem "rubocop-rails"
  gem "rubocop-performance"
  gem "rubocop-rspec"
  gem "rubocop-rake"
end

group :development do
  gem "web-console"
  gem "annotate"
end
