name: Publish to NPM/RubyGems
on:
  release:
    types: [created]
jobs:
  npm_module:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for npm trusted publishing
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24.x"
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - run: yarn
      - run: npm version --no-git-tag-version $(echo $GITHUB_REF_NAME | cut -c 2-)
      - run: yarn build
      - run: npm publish
  gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: sed -i "s/0.0.1/$(echo $GITHUB_REF_NAME | cut -c 2-)/" lib/shimmer/version.rb
      - name: Publish gem
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
